// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClQD3dbUyMfalkq4d0P19v8u2DUURfhr4',
    appId: '1:141322596755:android:cfaeab1d93013ad959f866',
    messagingSenderId: '141322596755',
    projectId: 'quietzone-4f8d0',
    storageBucket: 'quietzone-4f8d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSWL6rY_zfzM0KXWGfl_3i7H5wicjVUt8',
    appId: '1:141322596755:ios:49c822fdf63025f159f866',
    messagingSenderId: '141322596755',
    projectId: 'quietzone-4f8d0',
    storageBucket: 'quietzone-4f8d0.firebasestorage.app',
    iosClientId: '141322596755-hornic6cuov5d2bs61kivrm9jgkp519u.apps.googleusercontent.com',
    iosBundleId: 'com.example.quietZoneApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcpRfH4RB6-fFHUe1onpuGgeX3rZV2S8A',
    appId: '1:141322596755:web:11ea439b58be183059f866',
    messagingSenderId: '141322596755',
    projectId: 'quietzone-4f8d0',
    authDomain: 'quietzone-4f8d0.firebaseapp.com',
    storageBucket: 'quietzone-4f8d0.firebasestorage.app',
    measurementId: 'G-KDMGJFFQ66',
  );

}