import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  // Other code...
  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      // Other code...
      body: Container(
        // Other code...
        decoration: BoxDecoration(
          color: Colors.black.withOpacity(isDark ? 0.2 : 0.06), // Updated
          // Other code...
        ),
        // Other code...
      ),
      // Other code...
    );
  }

  // Other code...
}

// Other code...
